### ISSUE TITLE
Adding property has no effect

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-geodb#19] opened 2021-12-15 13:33 UTC
When adding a property to a collection, this seems to have no effect at all - but no error is thrown. 

To reproduce: use introduction notebook from EDC (https://eurodatacube.com/marketplace/notebooks/curated/EDC_GeoDB_1_manage-datasets_v11.ipynb)

![image](https://user-images.githubusercontent.com/23457217/146195669-310e4aad-671f-4a48-8774-0e4fd016c8d9.png)

and

![image](https://user-images.githubusercontent.com/23457217/146196085-6a5cb954-2909-47f5-8c25-5c3ab0cb5efc.png)

**Comment by thomasstorm** [comment] 2022-03-18 16:39
This seems to be caused by get_properties to be wrong - geodb.get_properties('land_use') should return id, created_date, updated_date and geometry in line 19.

**Comment by thomasstorm** [comment] 2022-04-12 20:49
This was already fixed in the code, but deployment to the production system was missing. This is now done -> closing.

**Closed by thomasstorm** 2022-04-12 20:49 UTC
